[package]
name = "craes"
version = "0.0.1"
authors = ["Daniel Bischof <daniel.bischof@protonmail.com>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
tokio = "*"
tracing = "*" 
tracing-futures = {path = "../tracing/tracing-futures"}
tracing-fmt = {path = "../tracing/tracing-fmt"}
futures = "*"
tungstenite = "*"
tokio-tungstenite = "*"
capnp = "*"
capnp-futures = "*"

[build-dependencies]
capnpc = "*"
